### ISSUE TITLE
Add tags to default template

### ISSUE THREAD

**Issue by chkw-rks** [vvvv/VL.NewLibrary.Template#2]
I suggest to also add "dotnet", "visual-programming" and "creative-coding".

The topic versions with dashes seem to be far more popular than the tags in which the space is left out, see here:

https://github.com/topics/creativecoding
https://github.com/topics/creative-coding

https://github.com/topics/visualprogramming
https://github.com/topics/visual-programming

**Comment by joreg** [comment]
where exactly do you suggest to add these?

**Comment by chkw-rks** [comment]
In the tag section of the GitHub repository.

**Comment by joreg** [comment]
ok, i'm afraid i don't think that's a good idea. it would spam the tag system with not really good associations. like e.g. vl.devices.Foo repo doesn't really help if someone is looking for any of the suggested tags.

**Comment by chkw-rks** [comment]
Alright!
